### ISSUE TITLE
Игровое пространство

### ISSUE THREAD

**Issue by Mitbus** [bmstu-iu9/utp2019-2-2d-game#10]
- Хранит информацию о всех блоках и мобах, которые содержатся в нем
- Координаты каждого блока будут хранится в координатах мира
- Карта освещения (передний слой)
- Имеются 4 слоя: 0 - игрок, -1 - задний фон, 1 - передний фон, 2 - освещение (полупрозрачные блоки)

**Comment by Mitbus** [comment]
Дополнительно блоки должны реализовывать: 
- [x] Параметры блоков:
- id(конкретный тип блока, например листва дуба), 
- общий тип блока (земля, камень, дерево, листва, жидкость), 
- координаты блока, 
- крепость, 
- светимость, 
- наличие коллизии, 
- возможность спрыгнуть с него в низ(как в платформерах)
- [x] Класс блок должен реализовывать методы:
- правый клик
- левый зажатый клик (разрушение)

**Comment by Shaniser** [comment]
Корректировка:
map должна иметь лишь массив id
А отдельно в геймареа должен храниться ассоц массив id -> блок с соответствующим id
И да, координаты не нужны в этом случае в свойстве блока

**Comment by Shaniser** [comment]
Также нужна реализация статических констант MAIN_LAYOUT, BACK_LAYOUT, FORWARD_LAYOUT в классе GameArea

**Comment by Shaniser** [comment]
Добавить gameArea.width и gameArea.height в конструктор и как константы для экземпляра класса
