### ISSUE TITLE
Внутриигровой таймер

### ISSUE THREAD

**Issue by whitequartz** [bmstu-iu9/utp2019-2-2d-game#105]
Необходимо добавить независимый таймер со своим `deltaTime` (даже, если будет таймер с константным шагом), на который нужно перенести расчёт камеры, движения игрока, обновления в мире (вода, лава и прочее), чтение данных с мыши и клавиатуры и другое.
Желательно всё сразу перенести на этот таймер.
**Старый `deltaTime` использовать строго для отрисовки и всё что с ней связано! Цикл `update` не предназначен для обработки любых данных, кроме отрисовки! Браузеры для экономии ресурсов могут его останавливать или замедлять (особенно на ноутбуках)!**
Можно сделать несколько таймеров, например, более быстрый для обновлений, связанных с игроком (т.к. он может перемещаться), а более медленный для обновления блоков (чтобы повысить производительность).

**Comment by Mitbus** [comment]
старый deltaTime не используется для отрисовки, по сути он тогда вообще не нужен. А `newDeltaTime` будет тогда константой

**Comment by Mitbus** [comment]
На данный момент для всех обновлений в мире я использую свои таймеры по необходимости с различными интервалами
