### ISSUE TITLE
Не уничтожаются блоки

### ISSUE THREAD

**Issue by Mitbus** [bmstu-iu9/utp2019-2-2d-game#107]
При любом взаимодействии с блоками в `develop` и `interface` вылетает ошибка: `undefined has no properties`

**Comment by Shaniser** [comment]
У меня нет)

**Comment by Shaniser** [comment]
Диагностируй у себя

**Comment by Mitbus** [comment]
У меня так только в одном браузере в сохранении, которое было сделано до вчерашних изменений. Вероятно, какое-то поведение больше не сочетается со старым
