### ISSUE TITLE
Мобильные устройства

### ISSUE THREAD

**Issue by Mitbus** [bmstu-iu9/utp2019-2-2d-game#111]
- [ ] После появления меню (#32) добавить и реализовать пункт "наэкранные кнопки управления" 
- [ ] Отслеживать событие нажатия на сенсорный экран как альтернативу клика мыши

**Comment by Mitbus** [comment]
Но боюсь, что в этом случае придется перенести быстрый инвентарь и бары в верхнюю часть экрана, а вниз поместить кнопки перемещения

**Comment by Mitbus** [comment]
Еще есть предложение изменить поведение кликов: будет доступен только ЛКМ, но если в руке то, что можно поставить - оно ставится, иначе - разрушается указанный блок. Такое управление будет удобнее на мобилках. Также это решит проблемы с ПКМ в некоторых браузерах
upd. Загрузил в ветку `test` это предложение, можно потестировать

**Comment by Shaniser** [comment]
Я против, если честно, всей этой затеи
Вы ухудшите то, что есть, и вряд-ли получите что-то рабочее.
Ты забыл про взаимодействие
Вместо того, чтобы открыть сундук ты будешь его ломать

**Comment by Mitbus** [comment]
Взаимодействие решается достаточно просто за счет разных событий клика, а вот по времени уже не успеваю это сделать, поэтому закрываю
