### ISSUE TITLE
Подсказки

### ISSUE THREAD

**Issue by Shaniser** [bmstu-iu9/utp2019-2-2d-game#112]
Нужно написать логику для подсказок на основе нижеописанного вывода сообщений

(Реализовано):
Вывод нужного сообщения на экран командой
showFloatMessage("str") ;
Строки в тексте (через "\n") нужно писать в обратном порядке желаемому выводу, только символами, представленными в font.png

Пока приходит сигнал showFloatMessage("str") - пишет
Если секунду не приходит - убирает
При смене сообщения убирает и выводит
С анимациями, как надо 

Вторым аргументом showFloatMessage("str", 10) можно передать минимальное время (в сек), которое сообщение продержится на экране если его не перекроют другим сообщением

**Comment by Mitbus** [comment]
В `develop`, если вызвать новое сообщение (другое по содержанию), пока не закрылось старое, то новое сообщение закрывает старое, но само не показывается

**Comment by Shaniser** [comment]
Да, его надо спамить до полного закрытия

**Comment by Mitbus** [comment]
Неправильно определяется конец подсказки, если использовать `\n`. Рамка отрезает часть текста в конце

**Comment by Shaniser** [comment]
Посмотри там сам в чем дело

**Comment by Mitbus** [comment]
Как? Я понятия не имею, как там все работает, а там 3 к строк кода

**Comment by Mitbus** [comment]
Я понял, длина задается как среднее значение длин всех строк, поэтому при неравномерном отрезании строк так происходит. Тогда встает вопрос: будем резать строку равномерно или определять конец по наибольшей строке?

**Comment by Mitbus** [comment]
Пока передаю все в одну строчку. Как быть, если на данный момент выполняются условия сразу для двух подсказок? Если спамить их вместе, то они перебивают друг друга

**Comment by Mitbus** [comment]
Сделал так, чтобы новая подсказка перекрывала старую. А подсказки пока влазят в одну строку, если что - буду переносить равномерно

**Comment by Mitbus** [comment]
Добавил способ обработки всех подсказок из одного массива `prompt.js`, там лежат несколько основных подсказок. Какие есть идеи для новых подсказок (что не понятно при первом знакомстве с игрой)? Еще хочу добавить кнопку, на которую будет отображаться краткая справка по управлению и пр.

**Comment by whitequartz** [comment]
> Добавил способ обработки всех подсказок из одного массива `prompt.js`, там лежат несколько основных подсказок. Какие есть идеи для новых подсказок (что не понятно при первом знакомстве с игрой)? Еще хочу добавить кнопку, на которую будет отображаться краткая справка по управлению и пр.

Мне кажется нужно:
1) Подсказка об управлении на A/D - влево/вправо, W - прыжок, до тех пор, пока игрок не нажмёт одну из этих кнопок
2) Подсказка об переходе на другой слой на S (вроде уже есть)
3) Подсказка об открытии инвентаря и окне крафта, после добычи первых блоков

**Comment by Mitbus** [comment]
1 и 2 уже есть, а 3 добавлю, спасибо

**Comment by Mitbus** [comment]
Добавил основные подсказки, по мере необходимости будем добавлять новые
