### ISSUE TITLE
Генерация мира

### ISSUE THREAD

**Issue by Mitbus** [bmstu-iu9/utp2019-2-2d-game#12]
Мир должен генерироваться по специальным ключам (натуральные числа).
Каждое отвечает за одну из возможностей ( можно объединить в одно число):
- размер в ширину
- размер в высоту фиксирован
- максимальное колебание уровня соседних блоков
Необходимо добавить:
- [x] генерация поверхности (#18)
- [x] генерацию пещер (#17)
- [x] генератор деревьев (#24)

**Comment by Shaniser** [comment]
Нужно объединить генератор мира в один файл
