### ISSUE TITLE
Работа с камерой движка

### ISSUE THREAD

**Issue by Mitbus** [bmstu-iu9/utp2019-2-2d-game#27]
- [x] Оптимизация отрисовки объектов: рисовать только ближайшие объекты
- [x] Использование чанков 16 х 128 (upd: 16х128 не оптимален. Необходимо подобрать оптимальный размер. См переменные chankWidth, chankHeight)
- [x] Представлять чанк в виде `{'chunk': [[...],...,[...]], 'x': 15, 'y': 7, 'slice': 8}` (см ниже)
- [x] Совместимость со второй версией движка
- [x] Автоматическая подстановка текстур
- [x] Добавить режим следования камеры (камера движется в указанную точку с нужной скоростью)
- [x] Добавить мгновенное перемещение камеры по координатам
- [x] Создать обертку для использования камеры

**Comment by Mitbus** [comment]
Добавил простые перемещения, но необходимо обсудить архитектуру. позднее разделю файлы по директориям

**Comment by whitequartz** [comment]
Чанк представлять в виде: `['chunk': [[...],...,[...]], 'x': 15, 'y': 7, 'slice': 8]`
* `chunk` - чанк
* `x, y` - координаты чанка
* `slice` - слой
В движок нужно будет передавать массив таких чанков, пример:
 `[['chunk': [[...],...,[...]], 'x': 15, 'y': 7, 'slice': 8], ..., ['chunk': [[...],...,[...]], 'x': 12, 'y': 4, 'slice': 1]]`

**Comment by Mitbus** [comment]
Баг при движении камеры: через небольшой отрезок времени камера останавливается и начинает моргать отображение текстур

**Comment by Mitbus** [comment]
Выяснилось, что массивы работают слижком медлено, следует работать с объектами тут и в #11

**Comment by Mitbus** [comment]
Чанк предоставлять в виде `{chunk: [[...], ... , [...]], x: ... , y: ... , slice: ... }`

**Comment by Mitbus** [comment]
Производительность улучшена (fps увеличился ~ на 50%)

**Comment by Mitbus** [comment]
Добавлен метод eventTick, который вызывается при каждой отрисовке объектов

**Comment by Mitbus** [comment]
Создана обертка для использования камеры. Всю логику уровня можно писать в level.js

**Comment by Mitbus** [comment]
Добавлен метод beginPlay
