### ISSUE TITLE
Работа с тенями

### ISSUE THREAD

**Issue by Shaniser** [bmstu-iu9/utp2019-2-2d-game#39]
- [x] Градиент общего освещения от поверхности к подземелью
- [x] Затенение скоплений блоков изнутри
- [x] Проработка искусственного освещения (факелы, лава и т.п.)
- [x] Смена дня и ночи
- Далее:
- [x] Мягкое освещение

**Comment by Mitbus** [comment]
Добавлен дополнительный слой (слой света - вызывает getLight(x,y)), который передается на рендер

**Comment by whitequartz** [comment]
Что нового:
* Починил освещённость после изменения формата принятия чанка освещённости
* Добавлено динамическое освещение
* Добавлено мягкое освещение
