### ISSUE TITLE
Загрузка таблицы блоков в gameArea

### ISSUE THREAD

**Issue by Irautak** [bmstu-iu9/utp2019-2-2d-game#40]
Загрузка таблицы происходила через node.js, что не работает в браузере.
Решения:
1) Прикреплять js файл с одной этой переменной отдельным файлом + я тогда закину на python прогу (нативный js не умеет файлы читать, угу), которая при запуске сама этот json-файл конвертит и создаёт скрипт, где только одна эта переменная в строку сжата
2) Cделать сервер на node.js,  но тогда надо не просто html страничку открывать, а запускать код сервера и вводить адрес по типу http://localhost:8080/index.html. Тогда сервер сможет node.js юзать и по запросу клиента (т.е всем скриптам, подключенным к html-странице) даст ему всё подгрузить

**Comment by Shaniser** [comment]
3. Хардкод в отдельном файле .js

**Comment by Irautak** [comment]
Это и есть первое, он создавать сам это код будет, по кнопке

**Comment by Shaniser** [comment]
Зачем? Зачем ещё питон туда? Непонятное усложнение жизни, я считаю

**Comment by Irautak** [comment]
Руками не очень удобно в js переменную всё писать, там строка без подсветки синтаксиса будет, а так просто в json всё красиво пишешь и кнопку нажимаешь. В любом случае, это костыльно, я за второй вариант сам. (К тому же я помню, как ты сам сказал, что не хочешь как код всё вставлять, я также считаю)

**Comment by Irautak** [comment]
В плане сервера : 
1. Создаём папку с сайтом, куда будем кидать все нужные файлы
2. Создаем файл server.js, там лежит логика, которая принимает запросы от клиента
3. Соответственно во всех скриптах можем отправлять запросы на этот сервер, просто для начала надо его запускать
Почему я за этот вариант - всё равно придется делать сервер когда-нибудь, а так надо будет только домен найти, если начать заниматься этим сразу

**Comment by Shaniser** [comment]
Пока юзаем третий вариант
