### ISSUE TITLE
Выбор блоков для игры

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2019-2-2d-game#6]
Выбрать, с какими блоками мы будем иметь дело

**Comment by Mitbus** [comment]
А как выбрать это?

**Comment by Mitbus** [comment]
Мы у каждой подзадачи можем ставить статус In progress? И как поставить его?

**Comment by Mazdaywik** [comment]
Когда эту заявку можно закрывать? Когда Вы опишете набор блоков для игры (не очень понял, что вы под этим подразумеваете) и создадите заявку вроде «Реализация блоков для игры».

**Comment by Mitbus** [comment]
понял, спасибо

**Comment by Mitbus** [comment]
Давайте минимальный набор блоков: замля, песок, камень, дерево. Пусть они имеют одинаковые свойста

**Comment by Shaniser** [comment]
Листва еще, очевидно

**Comment by Mitbus** [comment]
Потом мы можем добавить новые блоки и сделать свойства различными

**Comment by Mitbus** [comment]
еще какие свойства должны быть у блоков?

**Comment by Mitbus** [comment]
Чтобы мы их потом могли сделать разными?
