### ISSUE TITLE
Правила оформления кода

### ISSUE THREAD

**Issue by Mitbus** [bmstu-iu9/utp2019-2-2d-game#61]
Добавить правила стилизации кода, единые для всего проекта.
UPD: https://github.com/bmstu-iu9/utp2019-2-2d-game/wiki/Правила-оформления-кода

**Comment by whitequartz** [comment]
Создал правила оформления кода:
https://github.com/bmstu-iu9/utp2019-2-2d-game/wiki/Правила-оформления-кода
