### ISSUE TITLE
Предметы в инвентаре и взаимодействие

### ISSUE THREAD

**Issue by Mitbus** [bmstu-iu9/utp2019-2-2d-game#66]
- [x] Создать способ хранить внутреннее состояние инвентаря и взаимодействие с его элементами (#75)
- [x] Добавление блоков в инвентарь
- [x] Установка блоков из инвентаря, ломание блока выбранным предметом

**Comment by Mitbus** [comment]
Логика проверки на установку и уничтожение блоков дублируется в `level.js` и `player.js` с небольшими отличиями

**Comment by Mitbus** [comment]
Bug: Если собрать блок в инвентарь, взять его в руку, то предметы такого же типа будут уничтожаться слишком быстро

**Comment by Mitbus** [comment]
Bug: Дерево собирается не полностью, а только тот блок, который был сломан, хотя уничтожается целиком

**Comment by Shaniser** [comment]
> Bug: Дерево собирается не полностью, а только тот блок, который был сломан, хотя уничтожается целиком

С этим не сюда, пожалуйста

**Comment by Shaniser** [comment]
> Bug: Если собрать блок в инвентарь, взять его в руку, то предметы такого же типа будут уничтожаться слишком быстро

Исправляю
