### ISSUE TITLE
Модель игрока

### ISSUE THREAD

**Issue by Mitbus** [bmstu-iu9/utp2019-2-2d-game#68]
- [x] Добавить модель игрока
- [x] Анимация модели
- [x] Отображать выбранный предмет инвентаря

**Comment by Shaniser** [comment]
Нужна замедленная анимация для ходьбы

**Comment by Shaniser** [comment]
48x96 размерчики

**Comment by Shaniser** [comment]
![player](https://user-images.githubusercontent.com/48556605/61706561-0e934700-ad51-11e9-9fc7-1877a4938b86.png)

**Comment by Shaniser** [comment]
![Walking](https://user-images.githubusercontent.com/48556605/61706574-19e67280-ad51-11e9-9656-a6bc27326fbb.gif)

**Comment by Shaniser** [comment]
![Animation-2](https://user-images.githubusercontent.com/48556605/61708447-7cda0880-ad55-11e9-8831-c8ecc840f692.gif)

**Comment by Shaniser** [comment]
![Kick](https://user-images.githubusercontent.com/48556605/61710599-a0538200-ad5a-11e9-83da-36ffd0ca5737.gif)
(Возможно выглядит странно, но это удар инструментом, если что..) >_<

**Comment by Shaniser** [comment]
![Eye](https://user-images.githubusercontent.com/48556605/61710951-8ebeaa00-ad5b-11e9-938a-7bf07f776f57.gif)

**Comment by whitequartz** [comment]
Сделано отображение выбранного предмета инвентаря

**Comment by Mitbus** [comment]
Я думаю, что можно добавить несколько других анимации, если есть желание. Так, не хватает плавания, взгляд пока не используется и для Shift нет своей анимации

**Comment by whitequartz** [comment]
> взгляд пока не используется

Тогда я взгляд сделаю
