### ISSUE TITLE
Обработка ввода с клавиатуры

### ISSUE THREAD

**Issue by ylyxa** [bmstu-iu9/utp2019-2-2d-game#7]

**Comment by Mitbus** [comment]
Не уверен, что сюда, но коллизия проверяется по правому нижнему блоку игрока, те фактически можно залетать в блоки

**Comment by Shaniser** [comment]
А ещё он ходит поблоково, лол
Они вот так странно написали
Я вроде договорился с Владом, он делает

**Comment by Irautak** [comment]
Я пофиксил, вроде бы, кинул пулл-реквест с этим.
