### ISSUE TITLE
Сохранения

### ISSUE THREAD

**Issue by Mitbus** [bmstu-iu9/utp2019-2-2d-game#76]
- [x] Выяснить необходимые для продолжения игры переменные
- [x] Добавить возможность сохранения игрового процесса
- [x] Добавить возможность загрузки сохранения по  требованию

Все нововведенные переменные, которые необходимо сохранять можно писать комментарии

**Comment by Shaniser** [comment]
Обязательно к сохранению:
 * Seed
 * Изменённые чанки. UPD: карту освещения можно пересчитывать, так что она не нужна.
 * Координаты персонажа (возможно скорость)
 * Инвентарь

В будущем:
 * Сундуки
 * Лут на земле
 * Мобов
 * Растекающиеся жидкости

**Comment by Mitbus** [comment]
На данный момент будем сохранять:
- `gameArea.map`
- `player.x`
- `player.y`
- `player.vx`
- `player.vy`
- `player.inv`
Для сохранения изменений мира необходимо иметь механизм, позволяющий отслеживать эти изменения. Без изменений нецелесообразно хранить `key` (сид мира). Позднее, вместо всего `gameArea.map` можно хранить `key` и изменения в `gameArea.map` . Сундуки, лут и пр. пока не реализованы, поэтому сохранять пока нечего.

**Comment by Mitbus** [comment]
Добавил возможность загрузки одного сохранения. @Shaniser, все-таки JSON.parse превращает всё в строки и с объектами больше нельзя работать :(

**Comment by Mitbus** [comment]
По сути можно создать конструктор, который вытаскивает из полей все необходимые данные, но `player.js` и `gameArea.js` подразумевает полную копию кода. Если при рефакторе исправим их описание, то будет круто работать

**Comment by Mitbus** [comment]
Еще есть предложение передавать только изменяемы части объектов `gameArea` и `player`, которые точно не будут функциями. Это тоже должно решить проблему. Но в таком случае нужно знать имена всех новодобавленных полей, важных при загрузке ( после вчерашнего добавления инвентаря и пр.)

**Comment by Mitbus** [comment]
Решил вопрос последним способом, все работает, но при перезагрузке на вершинах кубов появляются точки ( можно посмотреть в ветке issue-77). Пока сохранение работает на СКМ и загружается при перезагрузке браузера

**Comment by Mitbus** [comment]
Есть идеи, почему это может происходить?
![Снимок](https://user-images.githubusercontent.com/37288286/61330987-9a751280-a829-11e9-9ba6-b2eb5c5fa079.PNG)
upd. Просвечивает не задний фон. Если разрушить дерево, то за ним после перезагрузки тоже появляются точки поверх заднего фона

**Comment by Shaniser** [comment]
1) Что такое СКМ?
2) Как сохраниться (у меня каждый раз новый мир)?

**Comment by Shaniser** [comment]
У меня при загрузке стабильно происходит это. Думаю, ты начинаешь вызывать update до подгрузки мира
<img width="540" alt="Снимок экрана 2019-07-17 в 13 38 21" src="https://user-images.githubusercontent.com/48556605/61369279-74d32200-a898-11e9-8f5e-77788cbf52c1.png">

**Comment by Mitbus** [comment]
![Снимок](https://user-images.githubusercontent.com/37288286/61372353-8cfa6f80-a89f-11e9-84f4-2fe5fff6df83.PNG)
Вызываю update только после сохранения результата. Мб дело в копировании из loadingResult, хотя его там, вроде бы, не происходит. Кстати, у меня таких проблем нет

**Comment by Mitbus** [comment]
bug: Заметил, что нет обработки ошибок при сохранениях больших миров

**Comment by Mitbus** [comment]
Все исправил. Подробнее в #86
