### ISSUE TITLE
Более продвинутый способ разработки

### ISSUE THREAD

**Issue by Shaniser** [bmstu-iu9/utp2019-2-2d-game#77]
Ветка develop является этапом тестирования (с возможными недочётами) перед попаданием в мастер. Pull requests в мастер будут именно оттуда.

@Mazdaywik, можно попросить аналогичную io ссылку для этой ветки, пожалуйста? Если это в принципе возможно, конечно. Нам будет значительно удобнее тестировать.

**Comment by Mazdaywik** [comment]
В смысле, io-ссылку?

**Comment by Mazdaywik** [comment]
Можно запинить, но запинить может любой. Не только я.

**Comment by Shaniser** [comment]
Понял, почитаю тогда, спасибо

**Comment by Mazdaywik** [comment]
Я рассказывал на лекции, что есть очень забюрократизированная модель разработки GitFlow, в ней вся работа ведётся в `develop`, а в `master` переносятся только релизы. Плюс определённые правила, как делать ветки фич и ветки багфиксов. Вот статья, где этот подход был впервые описан:
* <https://habr.com/ru/post/106912/>

Есть более простая модель разработки, которую я рекомендовал на лекции — GitHub Flow:
* <https://habr.com/ru/post/189046/> (эту ссылку я давал на лекции)
* <https://habr.com/ru/post/346066/> (эту ссылку я нашёл только что)

Почитайте и посмотрите, что вам удобнее.

**Comment by Mazdaywik** [comment]
А что Вы имели ввиду под io-ссылкой?

**Comment by Shaniser** [comment]
Github pages, судя по всему. Их можно не к мастеру подключить?

**Comment by Mazdaywik** [comment]
Да, я и забыл, что GitHub pages лежат на домене .io. Поэтому не сразу понял, о чём речь.

GitHub pages можно подключить к корню ветки `master` (как сейчас), корню ветки `gh-pages` или к подпапке `docs` в ветке `master`:
* https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages

Так что если хотите не `master`, то вместо ветки `develop` придётся использовать `gh-pages`.

**Comment by Shaniser** [comment]
Желание сделать отдельную ветку возникло в связи с правилами о том, что в мастере не должно лежать ничего недоделанного. Однако, так как почти все задачи очень тесно переплетаются, нам часто хочется использовать уже рабочий код другого человека, который(человек), например, ещё не доделал какие-то конкретные, не касающиеся нас аспекты, чтобы залить это в мастер

**Comment by Shaniser** [comment]
Кнопка настроек репозитория нам не доступна
Ладно, мастер, так мастер)
Все равно, на сколько я понял, два GitHub Pages для одного репозитория нельзя сделать

**Comment by Mazdaywik** [comment]
Если в вашей команде запрещена перезапись истории, то можете вливать себе код из чужой ветки. Просто `git merge чужая-ветка`. Если вы разрешаете перезапись истории в своих ветках, то это приведёт к жуткой путанице.

Кстати, если над конкретной задачей работает конкретный человек, то ветки принято называть как `имя-участника/название-ветки` или `имя-участника/issue-77`. К сожалению, я об этом не догадался сказать на лекции.

Запуште ветку `gh-pages`:
```
git checkout -b gh-pages develop
git push -u origin gh-pages
```
и я смогу переключить GitHub pages с `master`’а на неё.

(пока писал абзац выше, Вы обновили комментарий)

**Comment by Shaniser** [comment]
Сделал, переключите, пожалуйста

**Comment by Mazdaywik** [comment]
> Все равно, на сколько я понял, два GitHub Pages для одного репозитория нельзя сделать

Нельзя. Можно в ветке `gh-pages` создать несколько папок: `master`, `develop` и т.д. и написать скрипт, который в каждую из них коммитит верхушку соответствующей ветки. Ну и обращаться к ним по разным урлам.

**Comment by Mazdaywik** [comment]
Переключил.

**Comment by Mazdaywik** [comment]
Я только что посмотрел документацию, скрипт для подобной ветки `gh-pages` написать несложно.
```Batch
@echo off
git checkout gh-pages
git pull
git read-tree --prefix=master/ -u master
git read-tree --prefix=develop/ -u develop
git commit -m "%date% %time%" --allow-empty
git push
```
С небольшими изменениями скрипт будет работать и на unix-like (предпоследнюю строчку нужно будет переписать). Соответственно, урлы будут
* <https://bmstu-iu9.github.io/utp2019-2-2d-game/master>
* <https://bmstu-iu9.github.io/utp2019-2-2d-game/develop>

Дискламер: я его не запускал, поэтому работоспособность не гарантирую.

**Comment by Mazdaywik** [comment]
Закомитте в ветку `gh-pages` во-первых, сам скрипт, во-вторых, файл `README.md` следующего содержимого:
```Markdonw
* [Ветка `master`](master)
* [Ветка `develop`](develop)
```

**Comment by Mazdaywik** [comment]
Скрипт полезно закоммитить, чтобы можно было бы переключиться на ветку и обновить.
```Batch
git checkout gh-pages
update.bat
```
