### ISSUE TITLE
Улучшение поведения блоков

### ISSUE THREAD

**Issue by Irautak** [bmstu-iu9/utp2019-2-2d-game#78]
Планируется улучшить поведение воды и деревьев для более приятного эстетического восприятия:
- [x] При разрушении дна озёр вода должна разливаться корректно, не образуя неестественных углублений
- [x] Исчезновение воды без источника
- [x] Реализовать "слияние" потоков воды с разной наполненностью
- [x] Устранить баги с растеканием в воздухе
- [x] Корректное уничтожение деревьев и подсчет блоков
- [x] Ломание листвы без дерева
- [x] Замена травы и грязи при ломании
- [x] Обновление блоков после загрузки
- [x] Взаимодействие физики падения с растеканием воды ( +учет коллизий)
- [x] Промежуточные положения стоячей воды
- [x] Разлетание листвы дерева
- [x] Вода смывает некоторые блоки
- [x] Поддержка огня
- [x] Поддержка лавы
    - [x] Аналогично воде
    - [x] Свои параметры: плотность, текстура, пр.
    - [x] Сгорание блоков вокруг
    - [x] Взаимодействие с водой

**Comment by Mitbus** [comment]
Также при разрушении дна озер вода над уничтоженным блоком просто падает вниз  до первого препятствия, и только потом начинает разливаться

**Comment by Irautak** [comment]
Поток падает вниз, сам блок остается, всё вроде логично, как в Minecraft

**Comment by Irautak** [comment]
А, если что, вода БЕЗ ГРАВИТАЦИИ должна быть, там иначе тяжко поведение нормальное сделать, если от майнкрафтовской воды исходить

**Comment by Mitbus** [comment]
Есть предложение разделять дерево на естественное и поставленное игроком, чтобы нормально разрушалось только естественное дерево

**Comment by Mitbus** [comment]
Не знаю, как должна называться гравитация блоков, но в `gameArea` используется `hasGravity`, поэтому подправил ее с учетом света и добавил соответстующее поле в `items.js`

**Comment by Mitbus** [comment]
Сейчас деревья уничтожаются при взаимодействии с соседним блоков, по идее в `items.js` нужно добавить функцию, которая вызывается не при обновлении соседних блоков, а при взаимодействии именно с этим блоком, которая вызывается до уничтожения блока

**Comment by Mitbus** [comment]
Для новых промежуточных состояний воды было решено полностью переписать логику поведения воды

**Comment by Mitbus** [comment]
Исправил много мелких ошибок. Остается непонятно, как должна себя вести вода при попадании в нее блоков с физикой. Да и вообще, должна ли вода обратно становится источником при каких-то условиях.

**Comment by Mitbus** [comment]
Кажется, довел воду до ума в `modificated blocks`

**Comment by Mitbus** [comment]
Необходимо перерисовать текстуру каменной кладки (см демо в `develop`)

**Comment by Mitbus** [comment]
Внес изменения в `develop`
