### ISSUE TITLE
Альтернативы localStorage

### ISSUE THREAD

**Issue by Mitbus** [bmstu-iu9/utp2019-2-2d-game#79]
@Mazdaywik, мы хотим реализовать сохранение всего мира, а он весит очень много. Можем ли мы использовать что-нибудь кроме встроенных средств, например IndexedDB?

**Comment by Mazdaywik** [comment]
Она, как я понял из Википедии, поддерживается всеми современными браузерами. Так что можно. Я с современным web’ом не работал, поэтому не в курсе технических деталей. Может быть, @alex-qrcs здесь отпишется содержательнее.

**Comment by alex-qrcs** [comment]
https://localforage.github.io/localForage/
Рекомендую, у меня работало очень хорошо.

**Comment by Mitbus** [comment]
Вообще я уже начал использовать IndexedDB, но из-за асинхронности возникают некоторые проблемы. Думаю, благодаря похожему с localStorage синтаксису мы сможем быстро переписать под localForage

**Comment by Mitbus** [comment]
LocalForage не подходит из-за маленького сохраняемого значения(2-10 мб)

**Comment by Mazdaywik** [comment]
А зачем вам сохранять мегабайты? Откуда у вас столько данных берётся?

**Comment by Shaniser** [comment]
> А зачем вам сохранять мегабайты? Откуда у вас столько данных берётся?

У нас мир 3200х1500 блоков и в три слоя глубиной

**Comment by Shaniser** [comment]
Мы будем пытаться хранить минимум (например только изменения), но в худшем случае не влезем

**Comment by Mazdaywik** [comment]
Даже если по байту на блок, получается около 15 мегабайт. Можно, конечно, придумать алгоритмы компрессии, но для начала лучше реализовать «лобовое» решение.

Мир у вас генерируется каждый раз новый, поэтому можно, в принципе, сохранять зерно ГСЧ + дельту, обусловленную действиями игрока. Но это при условии, что игрок обычно не меняет все 3200×1500 блоков, а только малую часть их. Думаю, этот и подобные варианты вы уже рассматривали и без моих размышлений.

**Comment by Mitbus** [comment]
Все верно, но мы хотим, чтобы была честная возможность сохраниться при любых изменениях в мире. К тому же планируется добавить еще "большие миры", в которых будет более одного биома, а это может сильно увеличить мир. Также в планах добавить возможность не просто сохранять текущий прогресс, а иметь возможность хранить одновременно несколько миров. Еще в далеких планах есть мультиплеер.
Насчет оценки в 1 байт на блок: ради оптимизации мы просчитываем тени при генерации и храним их вместе с блоками, не стоит забывать, что в нашей игре 3 слоя блоков, а не один, а различных вариантов блоков, на данный момент, зарезервировано  до +\- 9000. По идее, мы можем упаковывать в один байт уже имеющиеся блоки ( их меньше 32) и тени ( 9 позиций на тень -> можем ужать до 8), но в перспективе их будет намного больше.
Все это заставляет нас не использовать `localStorage`, к тому же весь функционал (или почти), который мы могли бы использовать в варианте с `localStorage` уже реализован и работает на базе `IndexedDB`
