### ISSUE TITLE
Основы игрового мира

### ISSUE THREAD

**Issue by Mitbus** [bmstu-iu9/utp2019-2-2d-game#9]
Из чего состоит мир? Какие свойства есть у блоков? Есть ли что-то кроме блоков и игрока? Какие возможности есть у игрока?

**Comment by Mazdaywik** [comment]
Формулировка навевает на философские размышления 🙂.

**Comment by Mitbus** [comment]
Мир состоит только из блоков и игрока, позднее появятся мобы (возможно)

**Comment by Shaniser** [comment]
Параметры блоков:
id(конкретный тип блока, например листва дуба), общий тип блока (земля, камень, дерево, листва, жидкость), координаты блока, крепкость, светимость(возможно), наличие колизии, возможность спрыгнуть с него в низ(как в платформерах)

**Comment by Mitbus** [comment]
Свойства игрока:
движения(лево, право, прыжок - падение, вниз - спрыгивание как в платформере), направление (куда смотрит игрок - за мышью, те должны быть анимации поворота головы и туловища), инвентарь + выбранный предмет (для начала будем отрисовывать весь инвентарь всегда), расстояние досягаемости блоков (на какое место потягивается при разрушениии и постройке). В последствии: хп, дыхание, голод, интерфейс инвентаря (выбор одежды\ крафты)
