### ISSUE TITLE
Игра люто тормозит на Edge

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2019-2-2d-game#90]
В углу экрана показывается 3 FPS, игра реагирует на клавиши WASD с задержкой две-три секунды. Смотрел ветку `develop`. Компьютер нормальный, Intel® Core™ i5-2430M CPU @ 2.40 GHz, 8 Гбайт ОЗУ, Windows 10 x64.

**Comment by whitequartz** [comment]
В (#11) я на счёт этого уже занимаюсь

**Comment by Mitbus** [comment]
У меня в Edge производительность ниже конечно, но не так страшно (- 15-30%). Есть такие наблюдения: порой игра необоснованно тормозит даже на нормальном железе, а на ноутбуке слабее летает. Думаю, что дело может быть в ssd, либо во встроенной графике intel (на ноутбуке i5-8250U, говорят, что интегрированную графику серьезно подкрутили с 8-го поколения)

**Comment by Shaniser** [comment]
> В углу экрана показывается 3 FPS, игра реагирует на клавиши WASD с задержкой две-три секунды. Смотрел ветку `develop`. Компьютер нормальный, Intel® Core™ i5-2430M CPU @ 2.40 GHz, 8 Гбайт ОЗУ, Windows 10 x64.

А через любой другой браузер? Лучше? Или не пробовали? А то, может,  Intel® Core™ i5-2430M без дискретной карты слишком слабовато, чтоб хоть как-то с графикой работать..

**Comment by Mazdaywik** [comment]
Проблема у меня воспроизводится в любом браузере: Edge, двух сборках Хромиума (Спутник и Edge на Хроме) и свежем Firefox’е (обновил до последней версии, прежде чем запустить). На IE11 вообще пустой экран и 0 FPS в углу, про IE написал для полноты картины.

Оказалось, что у меня почему-то браузеры не используют процессор видеокарты (NVIDIA GeForce GT 550M). Вообще. Если смотреть на соответствующую вкладку в диспетчере задач — 0% использования и 0,0/6,0 ГБ памяти. Похоже, или ГП старый, или с драйверами глюк.

Но мы всё равно будем проверять на кафедре, а на кафедральной машине вроде всё работает.

**Comment by Mazdaywik** [comment]
Закрываю как **invalid,** поскольку проблема не в программе. Спасибо за то, что обратили внимание на проблему моей машины.

**Comment by whitequartz** [comment]
> Проблема у меня воспроизводится в любом браузере: Edge, двух сборках Хромиума (Спутник и Edge на Хроме) и свежем Firefox’е (обновил до последней версии, прежде чем запустить). На IE11 вообще пустой экран и 0 FPS в углу, про IE написал для полноты картины.
> 
> Оказалось, что у меня почему-то браузеры не используют процессор видеокарты (NVIDIA GeForce GT 550M). Вообще. Если смотреть на соответствующую вкладку в диспетчере задач — 0% использования и 0,0/6,0 ГБ памяти. Похоже, или ГП старый, или с драйверами глюк.
> 
> Но мы всё равно будем проверять на кафедре, а на кафедральной машине вроде всё работает.

Возможно в браузерах отключено аппаратное ускорение. В таком случае происходит эмуляция GPU на CPU, что очень затратно.
В многих браузерах можно в настройках включить аппаратное ускорение (в Edge и IE мне кажется, что нельзя это сделать в браузере).
В IE на MDN вместо стабильной версии WebGL говорится использовать экспериментальную, возможно из-за этого нет работоспособности. Я уже задумывался об включении экспериментальной версии, при невозможности включения стабильной. Практически все версии браузеров (основанные на Mozilla Firefox или на Google Chrome) от 2011 года поддерживают стабильную версию.
