### ISSUE TITLE
Третий слой?? Хмм.. (Идея для геймплейной фичи)

### ISSUE THREAD

**Issue by Shaniser** [bmstu-iu9/utp2019-2-2d-game#95]
Есть идея реализовать фишку с возможностью по кнопке перейти на 2ой слой. В этом случае возможно, например, первый слой делать полупрозрачным, а также отрисовывать третий слой (его уж точно не давать поменять игроку). Данная фишка позволит делать секретные проходы (в данжах, например), также можно генерировать деревья на рандомном из первых двух слоёв, т.к. их все равно можно будет обойти. Может являться достойной отличительной особенностью нашего шедевра.
Что думаете?

**Comment by Shaniser** [comment]
Думаю не стоит делать третий слой как таковой, а вот возможность переходить на второй слой очень даже можно было бы добавить

UPD: беру свои слова назад, с третьим куда прикольнее было бы

**Comment by Shaniser** [comment]
Сделал возможность перехода между слоями. Лежит в ветке Player

**Comment by Mitbus** [comment]
Ну уже обсуждали, всем понравилось. А 3 слой, вроде, решили сделать, если не придется много изменений вносить

**Comment by Mitbus** [comment]
Хотя если есть желание, то можно и переписать все для 3 слоя (если вообще есть потребность в этом)

**Comment by Shaniser** [comment]
Ок
Отлично
Вы развеяли мои сомнения, сээр

**Comment by Mitbus** [comment]
Я, кстати, изменений в `Player` не вижу

**Comment by Shaniser** [comment]
@Mitbus значит не заливал, сорян
Приеду домой, разберёмся

**Comment by whitequartz** [comment]
Нужно продумать реализацию. 
~~На данный момент, я слышал только предложение использовать третий слой как копию второго,  но без возможности изменений. За такую реализацию я против~~

**Comment by Shaniser** [comment]
@Mazdaywik, в чём прикол изменения названия?

**Comment by Mazdaywik** [comment]
http://www.gramota.tv/spravka/letters/87
https://www.primavista.ru/blog/2017/01/06/narashheniya-chislitelnyih
https://ilyabirman.ru/meanwhile/all/o-naraschenii-okonchaniy-chislitelnyh/

**Comment by Mazdaywik** [comment]
А прик0л и3менения в т0м, 4т0 не над0 в сл0вах 3аменять 6уквы на цифры. Сл0в0 «зий» нужн0 писать 4ере3 «з», а не цифру.

**Comment by Mitbus** [comment]
@whitequartz , по-моему имелось ввиду не копия второго слоя, а его передвижение на 3. Те создаем слой между 1 и 3, который совпадает с 3, а потом "вырезаем" в нем пещеры, данжи, руды и пр. (На самом деле так поступают и с 1 слоем, поэтому, возможно, ты подумал, что это его полная копия)

**Comment by whitequartz** [comment]
> @whitequartz , по-моему имелось ввиду не копия второго слоя, а его передвижение на 3. Те создаем слой между 1 и 3, который совпадает с 3, а потом "вырезаем" в нем пещеры, данжи, руды и пр. (На самом деле так поступают и с 1 слоем, поэтому, возможно, ты подумал, что это его полная копия)

Да, мне про это уже @Shaniser сказал

**Comment by Shaniser** [comment]
@Mitbus нужна помощь
