### ISSUE TITLE
Обновление фреймбуфера каждый кадр

### ISSUE THREAD

**Issue by whitequartz** [bmstu-iu9/utp2019-2-2d-game#98]
@Mitbus, абсолютно все чанки отрисовываются каждый кадр повторно, такого не должно быть.

**Comment by Mitbus** [comment]
В ветке `Graphical-Engine` все работает правильно

**Comment by Mitbus** [comment]
Ты как проверяешь то, что чанки отрисовываются каждый кадр? Я перед вызовом `render.drawChunk` ставлю `log`, они вызываются только при движении

**Comment by whitequartz** [comment]
Да, в ветке Graphical-Engine всё нормально. Проверялось в другой ветке и похоже некорректно слилось. Вопрос закрыт.
